id: AE4E72DEC
title: 'Victorious in the Battle with the Four Demons: A Prayer to the Lineage of
  the Wrathful Guru, Hayagrīva and Garuḍa'
type: translation
pechas:
- IC9E9B799
- I3328510B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:43.333339
  last_modified_at: 2023-01-04 11:27:43.333352
  collections:
  - Adzom Gyalse Series
  - Works of Tibetan Masters
alignment_to_base:
  IC9E9B799/C34C: '3449'
  I3328510B/1E1B: '3449'
